# Generated by Django 3.2.14 on 2022-09-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220904_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_Picture',
            field=models.ImageField(upload_to='profile_Picture'),
        ),
    ]
